rdkcentral/OneWifi

build/linux/makefile
build/linux/makefile.inc
build/linux/setup.sh

This change includes path changes in makefile to be compatible with github repositories. Also change to have the necessary repos required for compilation to be pulled as part of makefile setup command.

Additional changes for OneWifi compilation

---

include/webconfig_external_proto_easymesh.h
source/webconfig/wifi_easymesh_translator.c

Make associated client translation code compatible for multiple radios and vaps
Reason for change: Current code works with private_ssid_2g alone.
Test Procedure: Ensure associated client translation works without failure. Also removed unused code from translation functions.
Risks: Medium
Priority: P1
Signed-off-by: Rakhil P E

Make associated client translation code compatible for multiple radios and vaps

---

source/webconfig/wifi_easymesh_translator.c

Fix set channel change compilation errors
Reason for change: To fix build issues due to latest easymesh changes from https://github.com/rdkcentral/unified-wifi-mesh/pull/50
Test Procedure: Ensure translation function works fine.
Risks: Low

Fix set channel change compilation errors

---

include/wifi_base.h
source/core/wifi_ctrl.c
source/core/wifi_ctrl_rbus_handlers.c

Adds a OneWiFi `SendActionFrame` method that sends an action frame via the HAL and a new `X_RDK_mgmtFrameRecieved` event, which publishes data each time the HAL receives a management frame. 
The event allows applications to subscribe to `X_RDK_mgmtFrameRecieved` to process incoming management frames.

Add SendActionFrame function and mgmtFrameRecieved event

---

source/core/wifi_easy_connect.c

Reason for change:  Added Onewifi integration with BPI flags to resolve issues for BPI platforms.
Test Procedure: wifi sanity test cases(2G) are passed.
Risks: Low

RDKBACCL-403,RDKBDEV-2853 : Bringup onewifi in BPI Reference platform 

---

config/TR181-WiFi-USGv2.XML
config/subdoc_schemas_1_4/xfinity_subdoc_schema
source/core/wifi_ctrl_webconfig.c
source/core/wifi_multidoc_webconfig.c
source/dml/tr_181/ml/cosa_wifi_dml.c
source/webconfig/wifi_decoder.c
source/webconfig/wifi_encoder.c

OneWifi platforms
Reason for change: Implement Xfinity subdoc schema for Preassoc Tcm as  part of Epic
Test Procedure: Load the build and test the changes as per ACs
Risks: Low
Change-Id: Ic5eec8d8c28c87ada0a3e4702671343d1f427694 
Signed-off-by:Harshavardhan_Pulluru@comcast.com

RDKB-58072:Xfinity subdoc schema for Preassoc TCM

---

source/apps/analytics/wifi_analytics.c
source/apps/blaster/wifi_blaster.c
source/core/wifi_ctrl_webconfig.c

after multiple blast triggers
Reason for change: blaster webconfig state flag was not clear for device in gw mode.
Test Procedure: trigger blaster and check for overflow in the logs Risks: Low
Change-Id: Ibde1adcda7743a71f335256f241be7ff08597c66

RDKB-56356: wifiWebConfig.txt file size is increasing drastically

---

source/core/wifi_ctrl_webconfig.c

Reason for change: Enable EDPD for XER10 Platform as well.
Test Procedure: Check Eco Mode is working or not
Risks:Low

RDKB-58005: [ECOMODE] Enable Eco Mode Support For WiFi Radios

---

source/core/wifi_ctrl.c
source/core/wifi_ctrl.h
source/core/wifi_ctrl_queue_handlers.c

Reason for change: The acs_pending flag is not being cleared. Whenever the onewifi is restarted, it remains fixed on the previous channel.
Test Procedure: Checking the execution of Device.WiFi.WebConfig.Data.Init once the onewifi is restarted.
Priority: P1
Risks: Low
Signed-off-by: mothishree_mallaiyanjothimani@comcast.com
Change-Id: I6607a50ef42aa686bd8026e8d076690d2f342dbc

RDKB-57850: Unable to enable LEVL after FR

---

config/TR181-WiFi-USGv2.XML
include/wifi_base.h
source/core/wifi_ctrl_rbus_handlers.c
source/dml/tr_181/ml/cosa_wifi_dml.c

OneWifi platforms
Reason for change: Implement Rbus functions for TCM as part of Epic
Test Procedure: Load the build and test the changes as per ACs
Risks: Low
Change-Id: Id3b414554b23acfb3f685e7714270bcbb67adaa2 Signed-off-by:Harshavardhan_Pulluru@comcast.com

RDKB-58058: Telemetry and Rbus for Transient Client Management

---

source/apps/sm/sm_neighbor_cache.c
source/apps/sm/wifi_sm.c

Reason for change: SM App Neighbor logs enhancement.
1. Boot up the TCH XB8 with above mentioned build
2. Enable the Onewifi SM feature & also enable the SM debug using the following command • dmcli eRT setv Device.DeviceInfo.X_RDKCENTRAL-COM_RFC.Feature.SM_APP.Disable bool false • Touch /nvram/wifiSM
3. Check for the Neighbor logs in /tmp/wifiSM.
Risks: Low
Priority: P2
Change-Id: I7e40af6cf054ecb359e92167b9b7e2717bf25229 Signed-off-by:Sanjay_Venkatesan@comcast.com

RDKB-58055: wifiSM log improvement

---

source/stats/wifi_stats_radio_channel.c

Reason for change: SM sends dwell time zero for onchannel survey. Change dwell time to 20ms if requested dwell time is zero.
Test Procedure: Enable Onewifi SM and check for error message is not present.
"wlc_scan_on_dfs_chan: WLC_SCAN ignored due to less dwell time 10sec"
Risks: Low
Priority: P2
Change-Id: I6ac17ce4ca9b12b620b5dafb8cb8734caf500cbc

RDKB-58137: can errors console spam

---

source/webconfig/wifi_encoder.c

Association frame data is needed only when the client associates, so add that in the subdoc only during that time.
Change-Id: Ibe3ee428649efa6d925b9349e98052e28afd5577

Send Assoc frame data only when client associates

---

source/core/wifi_ctrl_rbus_handlers.c

Reason for change: Invalid data type is being passed to rbus publish function.
1. Load the above mentioned build.
2. Subscribe to this event like below, rbuscli -i
rbuscli> sub Device.WiFi.AccessPoint.2.X_RDK_deviceConnected
3. Connect a client to any of the private vap.
4. And check for the received event data is not null and contains mac address of the connected client.
5. If the data is null, then issue is reproduced.
Risks: Medium
Priority: P1
Change-Id: Id4de9aade2044cd02ae8ded8e95c836293fd6d8f Signed-off-by:Sanjay_Venkatesan@comcast.com

RDKB-58139: LEVL fingerprints are not reflected on CUJO portal

---

config/WifiSingleClientActiveMeasurement.avsc
source/apps/blaster/wifi_single_client_msmt.c
source/dml/tr_181/sbapi/webpa_interface.c

Reason for change: Adding support for 6G
Test Procedure: Trigger the blaster and check the metrics
Risks: None
Priority: P1
Change-Id: I3c725f6571d259a55151827a94c54b80002cdeb0 Signed-off-by:Pavithra_Sundaravadivel@comcast.com

RDKB-56120 Incorrect 6G radio blaster metrics sent to cloud

---

source/apps/whix/wifi_whix.c

Reason for change: Provider is executing before initial scan is complete
so adding a delay of 5sec to the provider function.
1. Load the device with the above mentioned build.
2. Verify for the ChUtilityLogInterval to be 15mins with the below command  dmcli eRT getv Device.DeviceInfo.X_RDKCENTRAL-COM_WIFI_TELEMETRY.ChUtilityLogInterval
3. Check for the WIFI_BANDUTILIZATION and CHUTIL markers in /rdklogs/logs/wifihealth.txt
Priority: P1
Risks: Low 
Signed-off-by: Samyuktha Karthikeyan <samyuktha_karthikeyan@comcast.com>
Change-Id: Ie15157b3fd275bef06014c2e1962704a4bd5d57c

RDKB-57697: WIFI_BANDUTILIZATION & CHUTIL markers are not coming.

---

source/apps/whix/wifi_whix.c

Impacted Platforms: All rdkb platforms
Reason for change: Used monitor variable instead of core variable in whix to fetch the vap enable status.
1. Load the device with above mentioned build.
2. Change the log interval to 15mins using below, dmcli eRT setv Device.DeviceInfo.X_RDKCENTRAL-COM_WIFI_TELEMETRY.LogInterval int 300.
3.Check the mesh backhaul status for 13th and 14th vap using,
dmcli eRT getv Device.WiFi.SSID.13.Status
dmcli eRT getv Device.WiFi.SSID.14.Status
4. Change the enable value of those backhaul vaps in Wifi_VIF_Config table by, /usr/opensync/tools/ovsh U Wifi_VIF_Config -w if_name==wl1.7 enabled:=true /usr/opensync/tools/ovsh U Wifi_VIF_Config -w if_name==wl0.7 enabled:=true
5. Check the status for mesh backhaul vaps again by following step 3.
6. Finally …

RDKB-58273: VAP UP PERCENT reports incorrect value for offline vaps.

---

source/core/wifi_ctrl_webconfig.c

When the feature flag FEATURE_SUPPORT_ECOPOWERDOWN is enabled, compiler error is seen in webconfig_hal_single_radio_apply function. This commit addresses that.

Fix compile error seen in webconfig_hal_single_radio_apply

---

source/apps/sm/wifi_sm.c
source/stats/wifi_stats_radio_channel.c

Impacted Platforms: All rdkb platforms
Reason for change: Dwell time has not been provided from stats config table while requesting the scan from SM App to monitor.
1.  Enable the mesh rfc dmcli eRT getv Device.DeviceInfo.X_RDKCENTRAL-COM_xOpsDeviceMgmt.Mesh.Enable
dmcli eRT setv Device.DeviceInfo.X_RDKCENTRAL-COM_xOpsDeviceMgmt.Mesh.Enable bool true
2. check the wifi stats config table ovsh s Wifi_Stats_Config -w radio_type==5G
ovsh s Wifi_Stats_Config -w radio_type==2.4G
3. Enable the SM App.
dmcli eRT getv Device.DeviceInfo.X_RDKCENTRAL-COM_RFC.Feature.SM_APP.Disable
dmcli eRT setv Device.DeviceInfo.X_RDKCENTRAL-COM_RFC.Feature.SM_APP.Disable bool false
4. Enable the OCS RFC for SM.
dmcli eRT getv Device.DeviceInfo.X_RDKCENTRAL-COM_RFC.Feature.OffChannelScan.Enable …

RDKB-58210: Incorrect survey scan interval.

---

source/webconfig/wifi_decoder.c

Reason for change: Frame Data absent in client subdoc is a valid scenario and should not be treated as error in decode. Frame Data will not be present in case of disassoc event.
Test Procedure: Ensured that the Error messages are not printed if framedata is absent.

RDKB-58478: Frame Data being absent in client subdoc not to be treated as error

---

source/apps/whix/wifi_whix.c
source/apps/whix/wifi_whix.h
source/apps/wifi_apps.c
source/stats/wifi_monitor.c

Impacted Platforms: All onewifi platforms
Reason for change: Implementation for XWIFI reject telemetry marker
Test Procedure: 1. Change the maximum client to 2.
2. Try to connect more than 2 clients.
3. Check the wifihealth.txt file.
Risks: Low
Priority: P1
Change-Id: Idc6365241d8559cdda14dcb1225697776ce27c27 Signed-off-by:RaviShankar.R_Rangaraj@comcast.com

RDKB-57124: XWIFI reject telemetry marker

---

source/webconfig/wifi_decoder.c

Reason for change: Crash was due to buffer overflow in accessing the input buffer.
Test Procedure: Checked connection and assoc data being encoded and decoded appropriately with easymesh agent and controller Risks: Low
Priority: P1

RDKB-58559: Address crash seen in stringtohex function

---

build/linux/setup.sh

halinterface was earlier pointing to a fork of rdkcentral. It is now changed to point to rdkcentral inline with other repos.

Change the location of halinterface to refer to rdkcentral

---

source/db/wifi_db.c
source/db/wifi_db_apis.c

Reason for change: Enable AKM suite selector 00-0F-AC:24 and GCMP-256 for pairwise cipher.
1. Load build
2. Verify wifi-5/wifi-6/wifi-7 client connectios in below modes
WPA3-Personal-Transition with 802.11be ON
WPA3-Personal-Transition with 802.11be OFF
WPA3-Personal with 802.11be ON
WPA3-Personal with 802.11be OFF
Priority: P1
Risks: Low

RDKB-58535: XCAM2 not able to connect(wifi7 interoperability)

---

source/apps/sm/sm_neighbor_cache.c
source/apps/sm/sm_utils.c
source/apps/sm/sm_utils.h
source/apps/sm/wifi_sm.c

Impacted Platforms: All RDKB platforms
Reason for change: Didn't include header "sm_utils.h" in wifi_sm.c and so compiler treats survey_type_to_str return type as integer instead of char pointer.
1. Boot up the device with above mentioned build
2. Enable the Onewifi SM feature & also enable the SM debug using the following command 
• dmcli eRT setv Device.DeviceInfo.X_RDKCENTRAL-COM_RFC.Feature.SM_APP.Disable bool false 
• Touch /nvram/wifiSM
3. Check for the crash in /tmp/wifiSM.
4. If crash occurs issue reproduced.
Risks: Low
Priority: P1

RDKB-58055: SM App optimization crash fix.

---

source/core/services/vap_svc_public.c
source/core/wifi_ctrl_queue_handlers.c

Reason for change: OneWifi changes for setting mode. Test Procedure: ACL set should work over Netlink.
Risks: Low
Priority:P0
RDKB-56764 RDKB-58193: ACL over NL80211 - 2.
Reason for change: OneWifi changes for setting mode. Test Procedure: ACL set should work over Netlink.
Risks: Low
Priority:P0
RDKB-56764 RDKB-58193: ACL over NL80211 - 2.
Reason for change: OneWifi changes for setting mode. Test Procedure: ACL set should work over Netlink.
Risks: Low
Priority:P0

RDKB-56764 RDKB-58193: ACL over NL80211 - 2.

---

source/apps/sm/sm_utils.c
source/apps/sm/sm_utils.h
source/apps/sm/wifi_sm.c

Impacted Platforms: All rdkb platforms
Reason for change: No existing prints for sample interval
reconfiguration.
1. Load the device with the above mentioned build.
2. Enable the SM App.
3. Verify the NOC push table with ovsh s Wifi_Stats_Config.
4. Change the sampling interval of any stats type and check the
logs in /tmp/wifiSM.
Risks: Low
Priority: P1

RDKB-58000 : Adding debugs for sample interval reconfiguration

---

source/db/wifi_db_apis.c

Impacted Platforms: New Platfroms - XB10/XER10/XER5
Reason for change: Some of the Xb10s are not taking the operating mode "g,n,ax" for 2.4G
Test Procedure: Set operating mode "g,x,ax" using tr181
Priority: P0
Risks: low

RDKB-58718: Unable to set operating mode "g,n,ax"

---

source/sampleapps/webconfig_consumer_apis.c
source/sampleapps/wifi_webconfig_consumer.c
source/sampleapps/wifievents_consumer_sample.c

Reason for change: Added code to release the memory. Test Procedure: 1) Execute below command from the console,
valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --log-file="/tmp/test.txt" --track-fds=yes /usr/bin/onewifi_component_test_app -d
2) After the execution, you can see the cli mode of the test app
3) Go to "/tmp/test.txt" and check for the definitely lost record in the file. Able to see the leak caused due to rbus_get call.
Risks: None

RDKBDEV-3060 REFPLTB-3245 REFPLTB-3246 REFPLTB-3244: Potential memory leak in method initial_sync at rbus_get

---

source/core/services/vap_svc_public.c

XB7, XB8
Reason for change: MgmtPower is reset sometime after reboot. Updating  values for xfinity vaps sometime after reboot.
Test Procedure: Set MgmtPower and reboot the device. Check if the same  value persists 10-15 mins after reboot
Risks: Low
Priority:P1
Change-Id: Ia3f9e15f7f54054b8e85a66099edcabac1b031be Signed-off-by:Amalesh_Nandh@comcast.com

RDKB-58155 Set MgmtPower for xfinity hotspot vaps

---

source/core/services/vap_svc_mesh_ext.c
source/core/wifi_ctrl.c

- Scan result wait timer is started two times:
1. Scan started for 3 radios.
2. First scan result starts scan_result_wait_timeout timer
3. Second scan result overwrites timer id and starts another scan_result_wait_timeout timer
4. Switch to GW mode cancels all timers but first timer still running
5. The timer starts STA connection while interface is in AP mode and fails
- Radio reset selfheal mechanism causes deadlock therefore removed:
1. recv_data_frame - lock hal lock - wpa_supplicant_event - wifi_drv_sta_set_flags - nl80211_read_sta_data - get_sta_handler - device_associated - wait for ctrl lock
2. ctrl lock - process_ext_connect_event_timeout - ext_reset_radios - wifi_radio_set_enable - wifi_hal_setRadioOperatingParameters - update_hostap_config_params - wait hal …

LTE-2475: fixed two STA connection scan timers

---

source/webconfig/wifi_ovsdb_translator.c

Reason for change: Opensync shouldn't handle hotspot associated clients. 
1. Configure hotspot.
2. Connect client to the hotspot.
3. Check MeshService logs for ""unexpected mutate count: 0 != 1"
4. Check the ovsdb associated clients table for the absence of the client.
5. Connect client to another vap.
6. Check the ovsdb associated clients table for presents of the client. 
Risks: Medium

RDKB-58152: Log Flood. unexpected mutate count: 0 != 1

---

source/utils/wifi_util.c
source/webconfig/wifi_decoder.c
source/webconfig/wifi_encoder.c

Reason for the change: Allows new vendor elements to be synced with other apps
Risks: Low
Priority: P0
Added ExtraVendorIEs item to Subdoc for adding additional vendor IEs + VAP refresh
**Depends on HAL PR [#21](https://github.com/rdkcentral/rdk-wifi-hal/pull/21) being merged/checked out!**
1. Apply the [webconfig_test_cce.patch](https://github.com/user-attachments/files/18697327/webconfig_test_cce.patch) patch from within the `OneWifi` directory.
2. Run `make -f build/linux/cce_makefile all` to build the testing application
3. Start OneWifi (`cd install/bin && sudo ./OneWifi -c`)
4. Start `cce` vendor IE adder: `sudo ./install/bin/cce --add`
5. Run the `unified-wifi-mesh` stack (controller + agent). 
6. Once they recognize each other the agent will begin sending subdocs which will …

RDKBWIFI-24: Added ExtraVendorIEs item to Subdoc for adding additional vendor IEs + VAP refresh

---

scripts/OneWiFi_Selfheal.sh

Reason for change: Syntax Error at the OnewifiSelfheal Test Procedure: Execute the below mentioned command after bootup.
grep -inr "unary operator expected" /rdklogs/logs/*
Priority: P2
Risks: Low
Signed-off-by: mothishree_mallaiyanjothimani@comcast.com

TCXB8-3555: Observing "unary operator expected" in the bootup logs

---

source/core/wifi_ctrl_rbus_handlers.c
source/dml/tr_181/ml/cosa_wifi_dml.c
source/platform/rdkb/bus.c
source/sampleapps/webconfig_consumer_apis.c

Reason for change: Fix warnings treated as errors in Kirkstone build.
Test Procedure: None
Risks: None
Priority: P1
Change-Id: I48813c8736c818708503566a76eaab6661c70dc3

XB10-1307 : Fix warnings treated as errors

---

build/linux/makefile
include/wifi_base.h
source/apps/easyconnect/wifi_easyconnect.c
source/apps/easyconnect/wifi_easyconnect.h
source/apps/wifi_apps.c
source/apps/wifi_apps_mgr.h
source/utils/wifi_util.c
source/utils/wifi_util.h

For publishing EasyConnect data relevant to third party applications (such as publishing frames containing CCE IEs for EasyMesh DPP). This is a replacement PR for #60 
See comments on that PR for previous discussion
-------------------------------
For testing:
```bash
cd Onewifi
export ONEWIFI_EASYCONNECT_APP_SUPPORT=1 && make -f build/linux/makefile all -j
```
A patch to pump hard-coded scan results onto each radio from the control thread:
```c
diff --git a/source/core/wifi_ctrl.c b/source/core/wifi_ctrl.c
index 8e0c136..19d7ddc 100644
--- a/source/core/wifi_ctrl.c
+++ b/source/core/wifi_ctrl.c
@@ -282,6 +282,60 @@ bool is_sta_enabled(void)
ctrl->eth_bh_status == false);
}
+#if 1
+static void send_fake_scan_event(wifi_ctrl_t *ctrl, int radio_index) {
+    wifi_bss_info_t *bss_info = …
```

Add EasyConnect app

---

include/wifi_base.h
source/apps/whix/wifi_whix.c
source/core/wifi_ctrl.c
source/core/wifi_ctrl.h
source/dml/tr_181/ml/cosa_wifi_internal.c

**Reason for change:** Use global configuration instead of `get_multi_vap_dml_parameters` because `set_multi_vap_dml_parameters` is not called on new platform.
**Test Procedure:**
1. Load XB10 with latest stable2 image
2. Once XB10 is up, check if Device.WiFi.X_RDKCENTRAL-COM_vAPStatsEnable is enabled
3. Set the WIFI_TELEMETRY.LogInterval to 300 seconds
4. Check if wifihealth.txt is available under /rdklogs/logs and clear the contents of file
5. Then run the script /usr/ccsp/wifi/aphealth_log.sh
6. Connect client to 2/5/6G SSID
7. Check the wifihealth.txt file
**Priority:** P1
**Risks:** Low

XB10-1266,RDKB-56567 : `WIFI_RECONNECT` telemetry not available in wifihealth

---

source/utils/wifi_util.c

Reason for change: Fixing build failure in OneWifi github code
Priority: P1
Risks: Low
Signed-off-by: SathishKumar Gnanasekaran
<sathishkumar_gnanasekaran@comcast.com>
Failure caused by this commit https://github.com/rdkcentral/OneWifi/commit/81c5c56b7292f0efd8bd59a79713c4c979b56eef

RDKB-58864: OneWifi github build failure

---

source/core/wifi_ctrl.h
source/core/wifi_ctrl_rbus_handlers.c

As UK version of XER10 doesn't support GFO(Gateway Fail Over) feature so GatewayManager process doesn't available. But we have seen GatewayManager related TR181 parameter requesting for subscription from OneWiFi/WiFiAgent/MeshAgent components. so we have introduced Device.X_RDK_Features.GatewayFailover.Enable TR181 for consumer.
1. PAM should work without any issue.
2. dmcli eRT getv Device.X_RDK_Features.GatewayFailover.Enable should provide result according to product support.
Risks: Low
Signed-off-by: Lakshminarayanan Shenbagaraj <lakshminarayanan.shenbagaraj2@sky.uk>

XER10-905 : Multiple logs are flooding.

---

source/webconfig/wifi_decoder.c

Impacted Platforms: All RDKB platforms
Reason for change: During Ccsp to OneWifi migration, there's no validation for the invalid characters in SSID.
1. Load the device with CGA4332COM_6.7p11s1_PROD_sey.
2. And CDL the device to CGA4332COM_7.6p6s1_PROD_sey
3. And check for the log print hal_cap.wifi_prop.numRadios is out of range is flooding in /rdklogs/logs/wifiDMCLI.txt.
Risks: Medium
Priority: P1

RDKB-58696: hal_cap.wifi_prop.numRadios is out of range(OW)

---

include/webconfig_external_proto_easymesh.h
source/webconfig/wifi_easymesh_translator.c

webconfig external proto changes for channel scanning
Reason for change: webconfig external proto changes to support channel scanning translation for easymesh
Test Procedure: Ensure both onewifi and agent builds are successful
Risks: Medium
Priority: P1

webconfig external proto changes for channel scanning

---

source/core/wifi_multidoc_webconfig.c

RDKB-58918: XFINITY Wifi SSID names are not getting changed via webconfig method
Reason for change: Fix validation failure for key ExtraVendorIEs
Test Procedure: Configure Passpoint webconfig from postman
Risks: Low

RDKB-58918: XFINITY Wifi SSID names are not getting changed via webconfig method

---

source/stats/wifi_monitor.c

Tech-XB7, Tech-XB8, CBRv2
Reason for change: moving info prints to dbg for logs
Test Procedure: Enable WPA3-Compatibility RFC and set security mode as
WPA3-Personal-Compatibility.
Check Client connectivity and internet
Risks: Medium
Priority:P1
Signed-off-by:Harshavardhan_Pulluru@comcast.com

RDKB-58443 RDKB-58446 Add WPA3-Compatibility Configuration and Telemetry

---

build/linux/EasymeshCfg.json
build/linux/MultiVap_InterfaceMap.json
build/linux/create_virtual_intf.sh
build/linux/makefile
source/core/wifi_ctrl.c
source/core/wifi_ctrl_rbus_handlers.c
source/db/wifi_db.c
source/utils/wifi_util.c
source/utils/wifi_util.h
source/webconfig/wifi_easymesh_translator.c

Reason for change: Support for configuring Onewifi to support below VAP configuration in Raspberry Pi
1) Private_5G using built-in Raspberry Pi Wifi adapter. 2) Raspberry Pi External Wifi adapter with SKU:RSP-PI-WIFI1 (Link: https://www.canakit.com/raspberry-pi-wifi.html) to support following VAP
- Mesh sta backhaul 2G
- Private_2G
- Guest AP using iot_ssid vap
- DPP configurator on lnf_psk vap
- Mesh VAP backhaul 2G 3) Necessary sample Json file for multivap configuration 4) Linux Makefile change to include label "vapsetup" to copy the configuration to appropriate location.
5) Change for sending bus error message in case of wrong configuration, in easymesh mode or easymesh colocated mode based on almac address.
Tested configuration with Canakit adapter and almac address …

RDKB-58602: [OneWifi]: MultiVAP, WiFi Backhaul as AL_MAC

---

source/stats/wifi_monitor.c
source/stats/wifi_stats_assoc_client.c

Reason for change: dml_parameters.rssi_threshold defined in wifi_mgr_t is not
initialized if NEWPLATFORM_PORT is defined.
This caused the wrong measurements for good and bad RSSI
times in WIFI_GOODBADRSSI_<AP index> in telemetry.
Also updating "Device.WiFi.X_RDKCENTRAL-COM_GoodRssiThreshold"
does not affect the time measurements.
Change the code to use GoodRssiThreshold directly in measurement.
Test Procedure: - Telemetry WIFI_GOODBADRSSI_<AP index> should contain correct
good and bad time measurements.
- Change of "Device.WiFi.X_RDKCENTRAL-COM_GoodRssiThreshold"
should affect the time measurement.
Risks: None
Priority: P2

XER10-1020 : WIFI_GOODBADRSSI marker incorrect

---

source/stats/wifi_stats_assoc_client.c

Removing unused variable 'rssi' to fix below build failure.
> 10:14:26  | ../../../git/source/core/../../source/stats/wifi_stats_assoc_client.c: In function 'execute_assoc_client_stats_api':
> 10:14:26  | ../../../git/source/core/../../source/stats/wifi_stats_assoc_client.c:166:9: error: unused variable 'rssi' [-Werror=unused-variable]
> 10:14:26  |   166 |     int rssi = 0;
> 10:14:26  |       |         ^~~~

XER10-1020 : Fixing build failure

---

source/stats/wifi_monitor.c
source/stats/wifi_stats_radio_channel.c

RDKB-58211-Removing OCS (off channel scanning) for secondary channels
Reason for change: Removed secondary channels from the list of channels for Off channel scanning.
1. Load the custom build
2. Verify that NOC push table "Wifi_Stats_Config" 
`/usr/opensync/tools/ovsh s Wifi_Stats_Config  -w radio_type==5G`
3. Check the correct working channel 
`wl -i wl1.1 chanspec`
4. check if the current working channel is DFS if yes disable the DFS 
`dmcli eRT getv Device.DeviceInfo.X_RDKCENTRAL-COM_RFC.Feature.DFS.Enable`
5. For testing purpose reduce sampling and reporting interval for 5G OCS
```
/usr/opensync/tools/ovsh u Wifi_Stats_Config -w survey_type==off-chan -w radio_type==5G -w stats_type==neighbor reporting_interval:=60
/usr/opensync/tools/ovsh u Wifi_Stats_Config -w …
```

RDKB-58211

---

source/apps/whix/wifi_whix.c

RDKB-59064: 6G_chan_width_split value is missing in wifihealth.txt
Reason for change: 6G_chan_width_split value is missing in wifihealth.txt
Test Procedure: Run command: cat /rdklogs/logs/wifihealth.txt | grep chan_width_split
Risks: Low
Priority: P1

Adding 320MHz channel bandwith case in OneWifi

---

build/linux/setup.sh

All OneWifi Platforms
Reason for change:We must dynamically update NAS IP to be in accordance with RADIUS IP Family.
Test Procedure: Enable Hotspot VAPs and connect clients. Simultaneously take erouter0 PCAPs. Check if NAS IP is updated properly as per RADIUS IP Family.
Risks: Low
Change-Id: I8f33dc2d45bef2dc10581c88d6b812a49f02dd9d Signed-off-by:Srijeyarankesh_JS@comcast.com

RDKB-58414: Dynamically update NAS

---

source/webconfig/wifi_decoder.c
source/webconfig/wifi_easymesh_translator.c

Reason for change: While webconfig decoding/encoding is possible for `ExtraVendorIEs`, they do not properly sync with EasyMesh.
Test procedure: 
Using correct version of `unified-wifi-mesh`, confirm that the `em_bss_info_t::vendor_elements`, `em_bss_info_t::vendor_elements_len`, `wifi_vap_info_t::u::bss_info::vendor_elements` and `wifi_vap_info_t::u::bss_info::vendor_elements_len` values are synced up after `webconfig_encode` and `webconfig_decode`
**Depends on unified-wifi-mesh [PR 219](https://github.com/rdkcentral/unified-wifi-mesh/pull/219)**

RDKBWIFI-24: Added translation for EM BSS vendor IEs  <-> HAL VAP vendor IEs

---

include/wifi_base.h
source/apps/em/wifi_em.c
source/webconfig/wifi_decoder.c

Reason for change: Easymesh agent supports max 16 neighbor scan results per scan results. Hence updating same in onewifi to fix the crash issue observed in easymesh agent due to buffer overflow. 
Test Procedure: Ensure channel scan results are received in agent side and then to controller cli upon request for channel scan. Risks: Medium
Priority: P1

RDKB-59209: EM App: Channel scan crash fix

---

source/ccsp/ccsp.c
source/ccsp/ccsp.h
source/ccsp/ccsp_api.c
source/db/wifi_db_apis.c
source/dml/tr_181/ml/cosa_wifi_internal.c
source/dml/wifi_ssp/ssp_loop.c

Reason for change: Added code to release the memory.
Test Procedure: 1) Added the change suggested in the ticket to generate the leak in the api which is calling during the service start.
2) Valgrind command is added in service file as given below,
ExecStart=/bin/sh -c 'valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes /usr/bin/OneWifi -subsys eRT.'
3) Increased the file size in journald.conf file
4) Stopped the service using systemctl command, it will be automatically try to restart using rpiwifiinitialized.path
5) Executed "journalctl -u onewifi" immediately with the stop command, redirected to some text file in the /tmp folder
Console command: "systemctl stop onewifi.service;journalctl -u onewifi > /tmp/leak_report.txt"

RDKBDEV-3061 REFPLTB-3230 REFPLTB-3233 REFPLTB-3234: Potential memory leak at PSM_Get_Record_Value2 call

---

source/core/services/vap_svc_mesh_ext.c
source/core/wifi_ctrl.c
source/core/wifi_ctrl_queue_handlers.c
source/core/wifi_ctrl_webconfig.c
source/db/wifi_db.c
source/db/wifi_db_apis.c
source/webconfig/wifi_decoder.c
source/webconfig/wifi_easymesh_translator.c

wifi_radio_operation_t structure has duplicate operating class variables op_class and operatingClass. Modify to use operatingClass and remove usage of op_class variable in OneWifi.
Test Procedure: ssid change, radio info change tested with Easymesh agent and controller.

RDKB-59259: Change to use operatingClass variable of wifi_radio_operation_t

---

source/apps/levl/wifi_levl.c
source/stats/wifi_monitor.c

Reason for change: To free the allocated memory after its usage
1. Flash the build in the issue device
2. Make sure Levl is enabled
3. Check for Memory Leak
Priority: P0
Risks: Low
Signed-off-by: Samyuktha Karthikeyan <samyuktha_karthikeyan@comcast.com>

RDKB-59288 Overall Memory usage is increasing continuously

---

source/db/wifi_db_apis.c
source/webconfig/wifi_ovsdb_translator.c

Reason for change: enable hostap mgt frame ctrl for xb10 and xer10 Test Procedure:
Risks: Low
Priority: P1

RDKB-59279: enable hostap mgt frame ctrl for xb10 and xer10

---

source/core/wifi_ctrl_rbus_handlers.c

Reason for change: This change is required to allow a device to begin in a state where it has not yet been onboarded. 
Test Procedure: Run `unified-wifi-mesh` with a bSTA Interface Map where the bSTA has not already been connected to a network.
Priority: P1
Risks: Low

RDKBWIFI-30: Fixed subdoc fetching fails for unassociated bSTA

---

source/webconfig/wifi_easymesh_translator.c

RDKB-59209: EM App - Fix typo in EM_MAX_NEIGHBORS
Reason for change: Fix typo in EM_MAX_NEIGHBORS
Test Procedure: Ensure channel scan results are received in agent side and then to controller cli upon request for channel scan.
Risks: Medium
Priority: P1

RDKB-59209: EM App - Fix typo in EM_MAX_NEIGHBORS

---

source/stats/wifi_monitor.c
source/stats/wifi_stats_assoc_client.c
source/utils/collection.c

RDKB-56194: OW hash map get crash
Reason for change: Missing mutex locks leads to race condition between threads in Onewifi.
1. Load the above mentioned build.
2. Connect clients to any of the private vaps and
3. Monitor for the crash in onewifi, if crash occurs issue reproduced.
Risks:medium
Priority: P1
---------

RDKB-56194:  Onewifi crash in hashmap get function. (#199)

---

source/db/wifi_db_apis.c
source/dml/tr_181/ml/cosa_wifi_dml.c

Reason for change: WPS enable is defaulted to true in CBRv2, so the value being set to true.
Load the above mentioned build in CBRv2.
Check the value of the wps by,
dmcli eRT getv Device.WiFi.AccessPoint.1.WPS.Enable If the value is true , issue is repoduced.
Risks: Medium
Priority: P1

RDKB-59230: WPS enable value is true for CBRV2

---

source/dml/tr_181/ml/cosa_wifi_dml.c

Reason for change: Able to set TCM values outside min and max range. However, no cap will be set for TcmGradientthreshold to help automation configure +ve and -ve values for Allow & Deny case

RDKB-58847:TCM values configurable outside range

---

build/linux/makefile
build/linux/setup.sh
build/linux/stamgr_setup.sh

Reason for change: Script change to pull stamgr as a seperate target
Test Procedure: Station manger code should checkout and build properly.
Risks: Low

RDKB-59277 : Push Station Manager code to WiFiStaManager repo.

---

source/db/wifi_db.c
source/utils/wifi_util.c
source/webconfig/wifi_ovsdb_translator.c

Reason for change: different mac filter mode triggers vap reconfiguration 
Check SSID is not reset to default after FR and SSID configuration.
Risks: Low
Priority: P1

RDKB-58944: set default mac filter mode configuration

---

source/platform/linux/he_bus/inc/he_bus_common.h
source/platform/linux/he_bus/inc/he_bus_data_conversion.h
source/platform/linux/he_bus/src/he_bus_core.c
source/platform/linux/he_bus/src/he_bus_data_conversion.c

Reason for change: HE bus command error code handle properly. Test Procedure: 1) Load OneWifi code on RPI.
2) Start easy mesh agent code.
3) Check HE bus get/set/sub/publish
is working properly.
Risks: Low
Priority: P1
Change-Id: Ib2866ecf273d97274ebe5ef08a4f83c6eddf6b0f Signed-off-by: apatel599@cable.comcast.com
(cherry picked from commit fa8619e6c810dfb652a452fc759500e8392e608c)

RDKB-57830: [OneWifi] HE bus command error code handling

---

source/db/wifi_db_apis.c

XB7, XB8, XB10
Reason for change: WPA3-Personal-Compatibility is not persisting reboot
Test Procedure: Set security mode to WPA3-Personal-Compatibility. Reboot the device and check if the configurations persists.
Risks: Low
Priority:P1

RDKB-59476 WPA3-Compatibility is not Persisting on reboot

---

source/webconfig/Makefile.am

Reason for change: This varaiable "EM_APP_FLAG" needs to be added in cflag if we enabled EM_APP_SUPPORT in libwebconfig Makefiles. 
Test Procedure: No core is forming
Risks: Low
Signed-off-by: keerthana.p <keerthana_pandurangan@comcast.com>

RDKBACCL-716 : onewifi is not up and running if extra_oemake=--enable-em-app enabled

---

source/db/wifi_db_apis.c
source/dml/tr_181/sbapi/cosa_wifi_apis.c
source/platform/common/data_model/wifi_dml_api.c

Reason for change: Migrating bootstrap.json from nvram to /opt/secure
Test Procedure: Check bootstrap.json is present in /opt/secure
Risks: medium
Priority: P1
Signed-off-by: Hirrangandhi_Devaraj@comcast.com

 RDKB-59380 : Migrating bootstrap.json from nvram to /opt/secure

---

build/openwrt/makefile

Reason for change: Adding in the openwrt makefile new file related to link metrics change.
Risks: Low
Test Procedure: Tested on BPI openWRT with 4Address usecase

RDKB-59404: OpenWRT related OneWifi additional change

---

source/db/wifi_db.c

RDKB-59512: Easymesh - Mesh BackHaul changes for colocated agent
Reason for change: To allow client connection in mesh_backhaul mac_filter_mode is changed to wifi_mac_filter_mode_black_list
Test Procedure: In colocated mode, if there is single vap at al mac address, ensure it is configured as mesh_backhaul
Risks: Medium
Priority: P1

RDKB-59512: Easymesh - Mesh BackHaul changes for colocated agent

---

source/db/wifi_db_apis.c
source/webconfig/wifi_decoder.c
source/webconfig/wifi_encoder.c

0 tx power value is invalid and leads to webconfig failure
root cause of 0 value unknown
Risks: Low
Priority: P1

LTE-2598: protection from tx power 0 value

---

source/apps/em/wifi_em.c
source/apps/em/wifi_em.h

Publish STA connection status for ingestion by unified-wifi-mesh when doing wireless mesh STA association via DPP or otherwise.

EasyMesh app: hook into wifi_event_hal_sta_conn_status

---

source/db/wifi_db_apis.c

Reason for change: Configuring BE operatingStandard support for 2GHz based the CONFIG_IEEE80211BE
Test Procedure: dmcli eRT getv Device.WiFi.Radio.1.OperatingStandards
Risks: None.

RDKBACCL-718 : Configuring BE operatingStandard for 2GHz

---

source/db/wifi_db_apis.c

Update new security mode after reboot
XB7, XB8, XB10
Reason for change: WPA3-Personal-Compatibility is not persisting reboot
Test Procedure: Set security mode to WPA3-Personal-Compatibility. Reboot the device and check if the configurations persists.
Risks: Low
Priority:P1

RDKB-59476 WPA3-Compatibility is not Persisting on reboot (#275)

---

source/db/wifi_db.c
source/db/wifi_db_apis.c

Reason for change:Change wifi db to default values set disable
Test Procedure: upon FR xhs should be disabled
Risks: Low
Priority: P1
Signed-off-by:risheesharma@gmail.com

RDKB-58922: [XHS] - After FR - 2.4Ghz XHS SSID is enabled by default

---

source/webconfig/wifi_easymesh_translator.c

RDKB-59556: 6 GHz radio configurations not working in EasyMesh
Reason for change: Fix the translation code for 6GHz band by changing WIFI_FREQUENCY_60_BAND to WIFI_FREQUENCY_6_BAND
Test Procedure: Ensure 6 GHz radio is configured as expected.
Risks: Medium
Priority: P1

RDKB-59556: 6 GHz radio configurations not working in EasyMesh

---

include/wifi_events.h
source/apps/em/wifi_em.c
source/apps/em/wifi_em.h
source/core/services/vap_svc.h
source/core/services/vap_svc_mesh_ext.c

Adds a new `connection_state_disconnected_steady` state to temporarily disrupt scanning during disconnection. Additionally adds EasyMesh add bus methods to set this state (if disconnected) and to kick back to the base `connection_state_disconnected_scan_list_none` state.
**Reason for change:** The constant scanning can cause action frames to not be sent or received sporadically. This allows the scanning state machine to be disrupted while other things (like the sending of action frames) occur. The disconnected scanning state machine can be initiated again later.
**Test Procedure:** Start OneWifi with no BSS for it to connect to (in the current version `/nvram/EasymeshCfg.json` must include which are empty strings). Then call `"Device.WiFi.EM.SetDisconnSteadyState"` and see in the debug …

RDKBWIFI-35: Add steady state to mesh service to disrupt constant disconnected scanning

---

source/webconfig/wifi_easymesh_translator.c
source/webconfig/wifi_webconfig_mesh_backhaul_sta.c

**Reason for change:** No method currently exists to **programmatically** connect a backhaul STA to a BSS from outside of OneWifi. By translating the mesh_backhaul_sta type (with a different BSSID), the `webconfig_send_sta_bssid_change_event` will be triggered, allowing the `services` state machine to begin associating the backhaul STA to the specified BSS. 
**Test Procedure:** Change the SSID, Password, and (most importantly to trigger the event) the BSSID in the `em_bss_info_t` struct and encode/update/apply it. OneWifi will take it and begin the state machine, associating to the given BSS.
**Risks:** None.
**Priority: P1**
**Depends on [**unified-wifi-mesh PR #329**](https://github.com/rdkcentral/unified-wifi-mesh/pull/329)**
**Packet capture of association with UWM backhaul AP** …

RDKBWIFI-34: Enable/implement mesh backhaul sta translations

---

source/core/wifi_ctrl.h
source/core/wifi_ctrl_rbus_handlers.c

Reason for change: observing below errors,
process_ext_sta_conn_status : bus_event_publish_fn(): Event failed in onewifi so, Continous Scanning is not happening.
Test Procedure: Mesh backhaul retry is happening
Risks: Low

RDKBACCL-728 : Mesh backhaul retry is not happened

---

source/core/services/vap_svc_mesh_ext.c
source/core/wifi_ctrl_rbus_handlers.c

Reason for change: IP check is not needed for EasyMesh usecase
Test procedure: Did not observe MeshBackhaul disconnection
Risks: Low

RDKBACCL-736: Mesh_backhaul disconnects due to station ip check

---

source/db/wifi_db.c

Reason for change: Added change to modify mac filter mode for mesh backhaul in hal layer.
Test Procedure: Ensure with mesh_backhaul, client device can be connected.
Risks: Medium
Priority: P1

RDKB-59512: Revert macfilter mode change for easymesh

---

source/apps/whix/wifi_whix.c

RDKB-59064: 6G_chan_width_split value is missing in wifihealth.txt
Reason for change: 6G_chan_width_split value is missing in wifihealth.txt
Test Procedure: Run command: cat /rdklogs/logs/wifihealth.txt | grep chan_width_split
Risks: Low
Priority: P1

Adding 320MHz channel bandwith case in OneWifi (#200)

---

config/rdkb-wifi.ovsschema
source/db/wifi_db_apis.c
source/webconfig/wifi_ovsdb_translator.c

All RDKB OneWiFi Platforms
Reason for change: Enable hostap_mgmt_frame_control by default.
Test Procedure: hostap_mgmt_frame_control should work fine and client connectivity should be successful.
Risks: Low
Priority: P1
Signed-off-by: Karthikeyan Nanjundan Karthikeyan_Nanjundan@comcast.com

RDKB-59135 Hostapd management frame control XB7 & XB8

---

source/core/wifi_ctrl_rbus_handlers.c
source/dml/tr_181/ml/cosa_wifi_dml.c
source/platform/rdkb/bus.c
source/sampleapps/webconfig_consumer_apis.c

Reason for change: Fix warnings treated as errors in Kirkstone build.
Test Procedure: None
Risks: None
Priority: P1
Change-Id: I48813c8736c818708503566a76eaab6661c70dc3

XB10-1307 : Fix warnings treated as errors (#132)

---

source/apps/whix/wifi_whix.c
source/core/wifi_ctrl_queue_handlers.c
source/core/wifi_ctrl_webconfig.c
source/db/wifi_db_apis.c
source/dml/tr_181/ml/cosa_wifi_dml.c
source/webconfig/wifi_decoder.c
source/webconfig/wifi_encoder.c
source/webconfig/wifi_ovsdb_translator.c

Reason for change: Moved WPS code under separate CFLAGS to enable for appropriate platforms.
1. Load the above mentioned build
2. If the loaded device supports WPS , then trigger the WPS push button led turns blue and client would connect via WPS.
3. If the loaded device doesn't support WPS, then trigger the WPS push button and verify the WPS didn't get triggered, if triggered then issue reproduced.
Risks: Medium
Priority: P1

RDKB-59244: WPS Enhancement task

---

source/apps/easyconnect/wifi_easyconnect.c
source/apps/easyconnect/wifi_easyconnect.h

EasyConnect implementors (such as unified-wifi-mesh) need to be able to parse beacons and probe responses and search for a given SSID to build their DPP Reconfiguration Announcement channel list
This expands the CCE IE HAL callback and publishes each BSS info heard for consumption / parsing by external apps
The reasoning for this logic can be found in Wi-Fi Alliance EasyConnect standard V3 section 6.5.2:
From the spec, specifically section 2.:
```
Enrollee -> Configurator: SHA-256(C-sign-key), group, A-NONCE, E'-id
Enrollees that send this message first derive a channel list for sending the DPP Reconfiguration Announcement frame
using the following steps:
1. Select preferred channels on which to send a DPP Presence Announcement frame to the broadcast address. For
interoperability …
```

wifi_easyconnect.c: add new path for BSS info publishing

---

config/TR181-WiFi-USGv2.XML
config/rdkb-wifi.ovsschema
lib/inc/schema_gen.h
source/db/wifi_db.c
source/db/wifi_db_apis.c
source/dml/tr_181/ml/cosa_wifi_dml.c
source/utils/wifi_util.c
source/utils/wifi_validator.c
source/webconfig/wifi_decoder.c
source/webconfig/wifi_encoder.c

Reason for change: Implement the following tr181's to support configuration of mlo params, these need to be added under Device.WiFi.AccessPoint:
mld_enable
mld_id
mld_link_id
mld_addr
mld_apply
corresponding to:
RDK_VENDOR_ATTR_MLD_ENABLE
RDK_VENDOR_ATTR_MLD_ID
RKD_VENDOR_ATTR_MLD_LINK_ID
RDK_VENDOR_ATTR_MLD_MAC
RDK_VENDOR_ATTR_MLD_CONFIG_APPLY
Test Procedure: mld_enable - true for mlo, false for slo mld_id - should be from 0 to 7 from private through mesh mld_link_id - link id of vap
mld_addr - should be bssid of vap for slo, should be bssid of first vap of the group in an mlo. mld_apply - should be 1 for the last vap in a group Priority: P1
Risks: high

RDKB-57769: wifi tr181 to mlo configuration

---

source/core/wifi_passpoint.c
source/dml/tr_181/ml/cosa_wifi_dml.c
source/webconfig/wifi_decoder.c

1.Logic to fetch and return Passpoint parameter values was missing in the implementation. 2.Added the missing logic to retrieve and return Passpoint parameter values when queried via dmcli.
1.Configure Passpoint settings.
2.Execute relevant dmcli commands.
3.Verify that the Passpoint parameters return expected values.
Risks: None
Priority: P1
Signed-off-by: akumar052@cable.comcast.com

RDKB-58759:Passpoint dmcli parameters don't report values

---

include/wifi_base.h
source/apps/whix/wifi_whix.c
source/apps/whix/wifi_whix.h
source/stats/wifi_monitor.c
source/stats/wifi_stats_assoc_client.c

Reason for change: Counting the bytes between two consecutive whix marker 
Test Procedure: Download some data and check if the same effected in 
WIFI_BYTESSENTCLIENTS_<vap_index> marker
Risks: None
Priority: P1
Signed-off-by:Pavithra_Sundaravadivel@comcast.com

RDKB-59580 Observed unexpected bytes and packets measurements in RDK logs (#303)

---

source/db/wifi_db_apis.c
source/webconfig/wifi_ovsdb_translator.c

HUB6 - SR213
Reason for change: Hostapd migration to 2.10 version for HUB6
Test Procedure: Verify HUB6 used hostapd 2.10 and verify client
connectivity.
Risks: Low
Priority: P1
Signed-off-by: Karthikeyan Nanjundan <Karthikeyan_Nanjundan@comcast.com>

RDKB-59133 Upgrade hostap to 2.10 version for HUB6

---

config/openwrt/banana-pi/InterfaceMap.json
config/openwrt/banana-pi/etc/init.d/onewifi
config/openwrt/banana-pi/wifi_interface_down.sh
config/openwrt/banana-pi/wifi_interface_up.sh

Few files which are required for onewifi execution on OpenWRT 1)InterfaceMap.json to depict the initial interfaces and mapping. 2)/etc/init.d/onewifi systemd related file
3)log_enablement.sh to enable certain important logging 4)wifi_interface_up.sh to bring up wifi interface with associated EasymeshCfg.json changes.
5)wifi_interface_down.sh to bring down wifi interfaces and cleanup.

RDKB-59404: OpenWRT related onewifi configuration

---

source/utils/wifi_validator.c
source/webconfig/wifi_decoder.c

RDKB-55802: [Passpoint] EAP methods configured for secure vAP are not seen in ANQP packet
Reason for change: Fix missing for updating eap method count and eap length
Test Procedure: Passpoint testing and check ANQP response frames
Priority: P1
Risks: No

RDKB-55802: [Passpoint] EAP methods configured for secure vAP are not seen in ANQP packet

---

source/core/wifi_multidoc_webconfig.c

Reason for change: 
1. Missing MLD configuration in the VAP object caused the parameters to fail validation.
2. Added the necessary MLD configs to vap_object handling to ensure successful processing.
1. Enable Passpoint.
2. Push the blob using Postman or WebConfig.
3. Verify that the SSID is updated as per the blob configuration.
Risks: None
Priority: P2
Signed-off-by: akumar052@cable.comcast.com

RDKB-59796 XFINITY wiFi parameters not updating via webconfig/postman on TXB8

---

build/openwrt/Makefile_package

This reverts commit 1fcf030eb94f34e1ea066ef49c3d57f07f7d4e5b as it is causing compilation issue in OpenWRT build.

Revert "RDKB-59859: Add TestSuite compilation (#344)"

---

config/TR181-WiFi-USGv2.XML
config/rdkb-wifi.ovsschema
include/wifi_base.h
lib/inc/schema_gen.h
scripts/OneWiFi_Selfheal.sh
source/db/wifi_db_apis.c
source/dml/tr_181/ml/cosa_wifi_dml.c
source/webconfig/wifi_decoder.c
source/webconfig/wifi_encoder.c

RDKB-59766: Onewifi Memory leak script
Reason for change: to restart the process when onewifi memory goes beyond threshold.
1. Load the above mentioned build.
2. Connect some clients to 2.4Ghz and 5Ghz band.
3. Monitor the RSS of onewifi memory.
Risks: Medium
Priority: P1
---------

RDKB-59766: Onewifi Memory leak [self-heal] script 

---

source/webconfig/wifi_ovsdb_translator.c

XLE-WNC
Reason for change: Added mutex lock to avoid race condition during encode and decode.
Test Procedure: Multiple reboot or software upgrade and verify VAPs are up and clients able to connect.
Risks: Low
Priority: P1

LTE-2656 SSIDs are enabled in tr-181 but vaps are down in driver level

---

source/db/wifi_db_apis.c
source/webconfig/wifi_ovsdb_translator.c

All RDKB OneWiFi Platforms
Reason for change: Enable hostap_mgmt_frame_control by default.
Test Procedure: hostap_mgmt_frame_control should work fine and client connectivity should be successful.
Risks: Low
Priority: P1

RDKB-59269 Enable hostap_mgmt_frame_control

---

source/db/wifi_db_apis.c
source/dml/tr_181/sbapi/cosa_wifi_apis.c
source/platform/common/data_model/wifi_dml_api.c

**RDKB-59380** : Migrating bootstrap.json from nvram to /opt/secure (#276)
**Reason for change:** Migrating bootstrap.json from nvram to /opt/secure
**Test Procedure:** Check bootstrap.json is present in /opt/secure
**Risks:** medium
**Priority:** P1

RDKB-59380 : Migrating bootstrap.json from nvram to /opt/secure (#276)

---

source/db/wifi_db_apis.c
source/dml/tr_181/ml/cosa_wifi_internal.c

Reason for change:  wifidb_init_vap_config_default called after Db read causing config to go back to default
Test Procedure: NA
Risks: Low

SHARMAN-3535 : WPS disable config failed to persist after reboot (#328)

---

scripts/OneWiFi_Selfheal.sh

RDKB-60024 Observed "integer expression expected" error message in SelfHeal logs
Test Procedure: After booting, grep -ir "integer expression expected" /rdklogs/logs/*
Priority: P1
Risks: No

Observed "integer expression expected" error message in SelfHeal logs

---

source/core/wifi_ctrl_rbus_handlers.c

Reason for change: Crash seen with OVSM due to webconfig exchange during init with dml subdoc for pod platforms
Test Procedure: No crash should be seen with ovsm

DTMESH-520 OVSM crash during OneWifi initialization

---

source/core/wifi_multidoc_webconfig.c

Reason for change: fix of memory leak
- send webconf blob multiple times
- check OneWifi memory is not growing Risks: Low
Priority: P1

RDKB-59797: fixed memory leak on webconf decoding (#334)

---

source/core/services/vap_svc_mesh_ext.c
source/core/wifi_ctrl.h
source/core/wifi_ctrl_webconfig.c
source/core/wifi_mgr.c

Reason for change:-
- changes to stop scanning if station is not present
- AP interface creation fails after successful backhaul connection in
Qualcomm device if a station interface is present not associated state.

DTMESH-515 changes to allow station deletion

---

config/rdkb-wifi.ovsschema
source/db/wifi_db.c
source/db/wifi_db_apis.c
source/dml/tr_181/ml/cosa_wifi_dml.c
source/webconfig/wifi_ovsdb_translator.c

Reason for change: Disable the wpa3 transition disable to support 6G clients roaming from WPA3-Personal
secuirty to WPA2-Personal AP's
Test Procedure: 1. Build images.
2. Configure 2.4/5G VAP's with WPA2-Personal.
3. Configure 6G VAP with WPA3-Personal.
4. Connect client to 6G VAP.
5. Roam client from 6G to 2.4/5G VAP's.
6. Client roaming should be successul
Risks: Medium
Priority: P1
Signed-off-by: apatel599@cable.comcast.com

RDKB-59745: Support for client roam from wpa3-p to wpa2-p

---

scripts/OneWiFi_Selfheal.sh
source/core/wifi_mgr.c
source/db/wifi_db_apis.c

Impacted Platforms: XLE only.
Reason for change: FR flag is not created for XLE ,so the global values are
zeroed instead of setting default values.
1. Do a Factory Reset.
2. Check OneWifi process
3. If process is getting restarted constantly, then issue is reproduced.
Risks: Low
Priority: P1

LTE-2673: SelfHeal constantly restarts OneWifi process after FR

---

include/wifi_events.h
source/apps/easyconnect/wifi_easyconnect.c
source/apps/easyconnect/wifi_easyconnect.h
source/apps/wifi_apps_mgr.h

Reason for change: 
- Currently there is no way to call `wifi_hal_startScan` from outside of OneWifi which is the only scanning method capable of scanning station interfaces. 
- Additionally, reduced the amount of publishers in the EC app due to redundancies. 
With the EC app built with OneWifi, call `Device.WiFi.EC.SendStaScan` while viewing `/tmp/wifiHalStats` and view the logs showing the scan was initiated.
Priority: P1
Risks: Low
Related to: 
- https://github.com/rdkcentral/rdk-wifi-hal/pull/228
- https://github.com/rdkcentral/OneWifi/pull/387

RDKBWIFI-39: Adds the ability to trigger station channel scan and consolidates results publishers.

---

scripts/OneWiFi_Selfheal.sh

XB7, XB8, CBR2, XB10
Reason for change: Update self_heal script to run force reset for private vap, only if Webconfig RFC status is up.
Test Procedure: Private vap should be force reset within 5-10 mins after webconfig is up if default SSID is set
Risks: Low
Priority:P1

RDKB-60228: Update self_heal script to run force reset for private vap

---

build/linux/rpi/setup.sh
build/openwrt/setup.sh

RDKB-60336: To sync build scripts used for RPI and BPI devices
Reason for change: To sync build scripts used for RPI and BPI devices
Test Procedure: Ensure onewifi build is successful for both RPI and BPI OpenWRT and Linux builds.
Risks: Medium
Priority: P1

RDKB-60336: To sync build scripts used for RPI and BPI devices

---

source/core/services/vap_svc_public.c
source/core/wifi_ctrl_queue_handlers.c
source/dml/dml_webconfig/dml_onewifi_api.c

TCXB8-3614 Observing empty value while fetching the mac entry using dmcli command
Reason for change: dml cache did not sync up with wifi management object at wifictrl
Push the hotspot configuration blob.
Disable the RadiusGreyList.
Enable the prefer private.
Connect the client with private ssid.
Check the hotspot mac filter entry.
Priority: P1
Risks: No
Signed-off-by: Dao Vu Tuan DaoVu_Tuan2@comcast.com

TCXB8-3614 Observing empty value while fetching the mac entry using dmcli command

---

include/wifi_base.h
source/core/wifi_ctrl_queue_handlers.c
source/core/wifi_ctrl_rbus_handlers.c

RDKB-59710 Resolve Sync issue for WPA3-PCM
XB7, XB8, XB10
Reason for change: Security Mode is not Synced with WEBPA when WPA3-PCM RFC is enabled
Test Procedure: Enable/Disable WPA3-PCM and check if notification is sent to webpa for security mode
Risks: Low
Priority:P1

RDKB-59710 Resolve Sync issue for WPA3-PCM

---

source/sampleapps/wifievents_consumer_sample.c

Reason for change: Improved sample APP csi data json file.
Test Procedure: 1. Load the OneWifi build.
2. Connect a station to gateway.
3. Execute the below command: $ wifi_events_consumer -e 7 -i 300 -n 20 &
-e 7 : subscribe to csi data
-i [csi data interval] : default 500ms min 100 max 30000 -n [num_of_samples to be written to a file]
4. check for the index by running the below data model command $ dmcli eRT getv Device.WiFi.X_RDK_CSI.
5. Provide input station mac address and enable CSI data collection by executing command, example as mentioned below $ dmcli eRT setv Device.WiFi.X_RDK_CSI.[index].ClientMaclist string F0:46:3B:5B:EF:D9 $ dmcli eRT setv Device.WiFi.X_RDK_CSI.[index].Enable bool true
6. As soon as the required samples are collected, wifi_events_consumer will be terminated. …

RDKB-60433: [Improved] Sample APP now saves CSI data in JSON format

---

build/openwrt/MT7966.config
build/openwrt/Makefile_package
config/openwrt/banana-pi/etc/init.d/onewifi
config/openwrt/banana-pi/wifi_interface_up.sh

Reason for change: OpenWRT config related change to enable virtual ethernet package in kernel. Makefile change to build libalsap and install necessary components in right path. onewifi procd script change for considering colocated_mode before overwriting the EasymeshCfg.json file.
Risks: Low
Priority: P1

RDKB-60367: OpenWRT related build changes for libalsap enablement

---

source/platform/linux/he_bus/inc/he_bus_common.h
source/platform/linux/he_bus/inc/he_bus_core.h

Reason for change: OneWifi crashes when a bus connection (like a `unified-wifi-mesh` agent or controller) disconnects. This occurs because larger "full names" (such as `Device.WiFi.CollectStats.Radio.{i}.ScanMode.*`) are larger than the pre-allocated buffer. The same can occur for the "name".
Risks: Low
Priority: P1
Additional info:
Crash Backtrace: (continues for any more frames)
```gdb
#0  0x00000055555c2988 in hash_map_remove (map=0x2e65646f2e6964, key=0x7ff0001052 "EasyMesh_service")
at /root/easymesh_project/OneWifi//source/utils/collection.c:221
#1  0x000000555562bddc in remove_client_existing_sub_info_cb (node=0x5556e0ab10, param=...)
at /root/easymesh_project/OneWifi//source/platform/linux/he_bus/src/he_bus_core.c:1267
#2  0x0000005555629924 in node_element_recurse_traversal …
```

RDKBWIFI-40: Fixes HE-Bus stack overflow

---

include/wifi_base.h
source/db/wifi_db_apis.c

All RDKB OneWiFi Platforms
Reason for change: Incorrect BssMax for XB hotspot VAPs
Test Procedure: Default BssMax for hotspot VAPs should be 5 for XBs.
Risks: Low
Priority: P1

RDKB-60397 Client Max Limit in XB10 devices are seen as 100

---

source/webconfig/wifi_easymesh_translator.c

Reason for change: vap_info structure has union of bss_info and sta_info structure. Based on the vap_mode access the union appropriately, otherwise fields will be accessed with wrong offset, causing undeterministic behavior.
Risks: Low
Priority: P1

RDKB-60494: EM Translator: Access bss_info structure only in vap ap mode.

---

scripts/OneWiFi_Selfheal.sh
source/core/wifi_mgr.c
source/db/wifi_db_apis.c

RDKB-60531: SelfHeal constantly restarts OneWifi process after FR
Impacted Platforms: XLE only.
Reason for change: FR flag is not created for XLE ,so the global values are
zeroed instead of setting default values.
1. Do a Factory Reset.
2. Check OneWifi process
3. If process is getting restarted constantly, then issue is reproduced.
Risks: Low
Priority: P1

RDKB-60531: SelfHeal constantly restarts OneWifi process after FR 

---

config/rdkb-wifi.ovsschema
source/db/wifi_db.c
source/db/wifi_db_apis.c
source/dml/tr_181/ml/cosa_wifi_dml.c
source/webconfig/wifi_ovsdb_translator.c

Reason for change: Disable the wpa3 transition disable to support 6G clients roaming from WPA3-Personal
secuirty to WPA2-Personal AP's
Test Procedure: 1. Build images.
2. Configure 2.4/5G VAP's with WPA2-Personal.
3. Configure 6G VAP with WPA3-Personal.
4. Connect client to 6G VAP.
5. Roam client from 6G to 2.4/5G VAP's.
6. Client roaming should be successul
Risks: Medium
Priority: P1
Signed-off-by: apatel599@cable.comcast.com

RDKB-59745: Support for client roam from wpa3-p to wpa2-p (#420)

---

source/db/wifi_db_apis.c

VAPs within the same MLO group are required to share the same MLO MAC (MLD_Addr).
The MLO MAC is designated as the MAC address of the primary MLO interface (the interface with MLD_Link_ID=0).
For VAPs operating in non-MLO mode (MLD_Enable = false), the VAP's individual MAC address is assigned as the MLD_Addr.
- Configure MLO group representing mlo_config 2 0 1 -1 dmcli eRT setv Device.WiFi.AccessPoint.1.MLD_Enable bool true dmcli eRT setv Device.WiFi.AccessPoint.1.MLD_ID uint 0 dmcli eRT setv Device.WiFi.AccessPoint.1.MLD_Link_ID uint 2 dmcli eRT setv Device.WiFi.AccessPoint.1.MLD_Apply bool false
dmcli eRT setv Device.WiFi.AccessPoint.2.MLD_Enable bool true
dmcli eRT setv Device.WiFi.AccessPoint.2.MLD_ID uint 0
dmcli eRT setv …

RDKB-60772: Implement proper mld_addr selection

---

scripts/OneWiFi_Selfheal.sh
source/core/wifi_ctrl.c

XB7, XB8, XB10
Reason for change: If SSID is defaulted, Force reset flag should be enabled to push private subdoc to the GW.
Test Procedure: Check if force reset flag in tmp dir exists in if SSID is default during bootup
Risks: Low
Priority:P1

RDKB-60904 Enable Force reset flag if SSID is defaulted

---

source/apps/cac/wifi_cac.c

Reason for change: Remove access to not initialized variables.
Test Procedure: onewifi crash shouldn't happen while connecting xfinitywifi clients
Risks: Low
Priority: P1

RDKB-60901: Xfinitywifi clients are unable to connect, onewifi crash

---

source/core/wifi_ctrl.c
source/core/wifi_ctrl.h
source/core/wifi_events.c
source/stats/wifi_monitor.h

* RDKB-0: fixed queue size and memory issues (8.2_p1xb10b)
Reason for change:increased control and monitor queue size to avoid events drops Test Procedure:
Risks: Low
Priority: P1
Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
* RDKB-0 : unknown events handle in ctrl-queue (8.2_p1xb10b)
Risks:
Priority:
Signed-off-by: poornakumar_mezhiselvam@comcast.com
* Update wifi_events.c
* Update wifi_events.c
added logs
* Update wifi_events.c
---------
Signed-off-by: Bogdan Bogush <bogdan_bogush@comcast.com>
Signed-off-by: poornakumar_mezhiselvam@comcast.com
Co-authored-by: Narendra Varma Dandu <narendandu@gmail.com>
Fix build issue (#500)
Signed-off-by: Narendra Varma <narendandu@gmail.com>
RDKB-60618: Fix build issue Update wifi_events.c(#502) …

RDKB-60618 : Wifi-Stats missing in wifihealth.txt / MARKERS not reported (8.2_p1xb10b)

---

source/webconfig/wifi_decoder.c
source/webconfig/wifi_easymesh_translator.c
source/webconfig/wifi_encoder.c

Due to the header changes in `em_base.h` this PR is dependent on unified-wifi-mesh [#418](https://github.com/rdkcentral/unified-wifi-mesh/pull/418) in order to build

RDKBWIFI44-45: Translate read-only vap_mode and vap_index to easymesh and allow passwordless station encoding/decoding

---

source/apps/cac/wifi_cac.c

Reason for change: Remove access to not initialized variables.
Test Procedure: onewifi crash shouldn't happen while connecting xfinitywifi clients
Risks: Low
Priority: P1

XB10-1912 : Xfinitywifi clients are unable to connect back post onewifi crash.

---

build/openwrt/setup.sh

Reason for change: Re enabled the kernel patch related to Channel change after making change not to create .rej file if the patch is already applied.
Risks: None
Priority: P1

RDKB-60610: OpenWRT: Channel change related kernel patch issue

---

source/apps/blaster/wifi_single_client_msmt.c

Reason for change: Adding NULL as default for enum
values
Test Procedure: Trigger blaster for offline client
and check the client stats
Risks: None
Priority: P1
Signed-off-by:Pavithra_Sundaravadivel@comcast.com
Change-Id: I0fbc4696648d97031f8d3eaa03081abe19eef3d1

RDKB-60611 Fill "NULL" for offline clients in blaster

---

source/apps/blaster/wifi_single_client_msmt.c

Reason for change: Setting NULL for offline clients
Test Procedure: Trigger blaster for offline clients
and check if its showing NULL in enum
parameters
Risks: None
Priority: P1
Signed-off-by:Pavithra_Sundaravadivel@comcast.com

RDKB-60611 Set params to NULL for offline clients

---

source/core/wifi_ctrl_webconfig.c

Reason for change: mesh cloud pushes delete of radio/STA interfaces.
Delete will set exists flag to false and trigger radio
reconfiguration. Reconfiguration disconnects all clients.
We can ignore exists flag change because radio/STA interfaces
should be always enabled and flag is only required for
Wifi_VIF_Config and Wifi_VIF_State sync.
Risks: Low
Priority: P1

RDKB-61031: ignore exists flag change for GW STA interface (#504)

---

source/db/wifi_db_apis.c

Reason for change: Corrected Wifi db log.
Test Procedure: 1. Build images.
2. Configure 2.4/5G VAP's with WPA2-Personal.
3. Configure 6G VAP with WPA3-Personal.
4. Connect client to 6G VAP.
5. Roam client from 6G to 2.4/5G VAP's.
6. Client roaming should be successul
Risks: Medium
Priority: P1

RDKB-61098: Support for client roam from wpa3-p to wpa2-p

---

source/core/wifi_multidoc_webconfig.c

XB8, XB10
Reason for change: WPA3-PCM is not supported for 6GHz. Only WPA3-Personal is applicable for 6GHz
Test Procedure: Set security mode as WPA3-PCM for private 6GHz and push the blob
Risks: Low
Priority:P1

RDKB-61027 WPA3-PCM should not be set for 6GHz

---

config/TR181-WiFi-USGv2.XML
config/rdkb-wifi.ovsschema
lib/inc/schema_gen.h
source/core/wifi_ctrl_webconfig.c
source/db/wifi_db.c
source/db/wifi_db_apis.c
source/dml/dml_webconfig/dml_onewifi_api.c
source/dml/dml_webconfig/dml_onewifi_api.h
source/dml/tr_181/ml/cosa_wifi_dml.c
source/utils/wifi_validator.c
source/webconfig/wifi_decoder.c
source/webconfig/wifi_encoder.c

RDKB-60953, BCOMB-3031: Add AMSDU TID handling
Reason for change: Implements handling of AMSDU TID
Test procedure: Verify build, set/get AMSDU TID, verify on rdk-wifi-hal side if message is received
Priority:P1
Risks: None

Add AMSDU TID handling

---

source/core/wifi_ctrl.c

XB10, XER10
Reason for change: Force reset flag should persist across reboot
Test Procedure: Check if force reset flag exists in nvram if SSID is default during bootup
Risks: Low
Priority:P1
---------

RDKB-60904 Enable Force reset flag if SSID is defaulted (#549)

---

source/db/wifi_db_apis.c

Reason for change: As part of XER10 ROI, as using same partner as sky-uk, when we set default country code as IE (Ireland), onewifi failed to set it. This occurred when we change default RegionCode in partners_defaults.json as IE for XER10 under sky-uk partner.
The issue is due to failure in copying default country code as IE in wifi_db_apis.c.
Here corrected the string copy opertauon to properly get the country code from bootstrap.json.
- Load the image
- Make sure default country code came as IE instead of GB for XER10 UK.
Priority:P1
Risks:Low

RDKB-60023: Failed to Set Default country code as IE for UK patner

---

include/webconfig_external_proto_easymesh.h
source/webconfig/wifi_easymesh_translator.c

RDKB-61233: Easymesh - WiFi 7 Integration
Reason for change: Add support for WiFi 7 SLO/MLO in Easymesh.
Test Procedure: Ensure basic easymesh configuration and client connectivity works for wifi7 clients.
Risks: Medium
Priority: P1

RDKB-61233: Easymesh - WiFi 7 Integration

---

config/TR181-WiFi-USGv2.XML
config/rdkb-wifi.ovsschema
lib/inc/schema_gen.h
source/core/wifi_ctrl_webconfig.c
source/db/wifi_db.c
source/db/wifi_db_apis.c
source/dml/dml_webconfig/dml_onewifi_api.c
source/dml/dml_webconfig/dml_onewifi_api.h
source/dml/tr_181/ml/cosa_wifi_dml.c
source/utils/wifi_validator.c
source/webconfig/wifi_decoder.c
source/webconfig/wifi_encoder.c

Reason for change: Implements handling of AMSDU TID
Test procedure: Verify build, set/get AMSDU TID
Priority: P1
Risks: None

RDKB-60953, BCOMB-3031: Add AMSDU TID handling (#538)

---

source/core/wifi_ctrl_queue_handlers.c

* RDKB-60984:Clients not connecting to private VAPs due to kick
OneWifi platforms
Reason for change: Kicking of clients is not proper.
Problem is hapd->stalist is updated even after receiving auth req frame from client by hostapd. So in some cases, client was being sent disassoc frame even when actually the client had not undergone any association. This caused the client to take some time before connecting again. Also, the NL to set mac address mode was missing which is essential for blocking mgmt frames in process_frame_mgmt. The scheduled event being of low priority somehow got starved and in extreme cases took >1 min for the scheduled event to be executed. Lastly, even when mac address addition failed in HAL call, the event still got scheduled only to be thrown …

RDKB-60984:Clients not connecting to private VAPs due to kick (#553)

---

source/webconfig/wifi_easymesh_translator.c

Reason for change: Added length check to prevent buffer overflow if frame data length is higher.
Test Procedure: Ensure no crash issues when client connects to network
Risks: Medium
Priority: P1

RDKB-61233: Easymesh Agent Crash Fix

---

config/TR181-WiFi-USGv2.XML
config/rdkb-wifi.ovsschema
lib/inc/schema_gen.h
source/core/wifi_ctrl_webconfig.c
source/db/wifi_db.c
source/db/wifi_db_apis.c
source/dml/dml_webconfig/dml_onewifi_api.c
source/dml/dml_webconfig/dml_onewifi_api.h
source/dml/tr_181/ml/cosa_wifi_dml.c
source/utils/wifi_validator.c
source/webconfig/wifi_decoder.c
source/webconfig/wifi_encoder.c

Reason for change: Implements handling of AMSDU TID
Test procedure: Verify build, set/get AMSDU TID
Priority: P1
Risks: None
This commit is a cherry pick of e14170830a58b6026ac21a1173e09512704d334e
from develop branch

RDKB-60953, BCOMB-3031: Add AMSDU TID handling (#538) - cherrypick

---

source/core/wifi_multidoc_webconfig.c
source/db/wifi_db.h
source/utils/wifi_util.c
source/webconfig/wifi_decoder.c
source/webconfig/wifi_encoder.c
source/webconfig/wifi_ovsdb_translator.c

Reason for change: Improved is_vap_configure_changed function logic to Avoids
checking pre-association, Passpoint, and ANQP configurations
for VAPs other than Hotspot VAPs.
Test Procedure:1. Load the OneWifi build.
2. Connect client with 2g/5g.
3. Wait until 5g channel optimizations trigger.
4. Check Client is connected back to 5g VAPs.
Priority: P0
Risks: Low
Signed-off-by: apatel599@cable.comcast.com
RDKB-59898: [OneWifi]WiFi Interfaces reconfigured post 5G channel optimization (#468)
Reason for change: Improved is_vap_configure_changed function logic to Avoids
checking pre-association, Passpoint, and ANQP configurations
for VAPs other than Hotspot VAPs.
Test Procedure:1. Load the OneWifi build.
2. Connect client with 2g/5g.
3. Wait until 5g channel optimizations trigger.
4. Check …

RDKB-59898: [OneWifi]WiFi Interfaces reconfigured post 5G channel opimization (#460) (#557)

---

source/webconfig/wifi_easymesh_translator.c

Reason for change: Add support to populate Backhaul STA Data during translation
Test Procedure: Ensure basic easymesh configuration and BackhaulSTA field being polulated in Controller's database
Risks: Medium
Priority: P1

RDKB-61667: Easymesh - Backhaul STA Data translation

---

source/core/wifi_ctrl.c

RDKB-61233, RDKBACCL-1098: Easymesh - AP MLD details not populated for extender DML subdoc
Reason for change: Added change to populate AP MLD details to onewifi from hal.
Test Procedure: Ensure AP MLD details are present in DML for extender device.
Risks: Medium
Priority: P1

RDKB-61233, RDKBACCL-1098: Easymesh - AP MLD details not populated for extender DML subdoc

---

source/core/wifi_ctrl_webconfig.c

Reason for change: On adding ACL MAC entry, create new ACL map if missing;
if the operation fails due to uninitialized VAP, defer
adding the ACL MAC entry until the VAP is created.
Test Procedure:1) Load the OneWifi build onto the device. 2) Add ACL Mac entries using DMCLI
3) Reboot device and verify ACL Mac entries.
Priority: P1
Risks: Low
Change-Id: I03d81ff76a98698b623a63cbc854b5448edb1f51
Signed-off-by: apatel599@cable.comcast.com

RDKB-61663:Unable to add POD to Tc XB7 and Tc XB8
