rdkcentral/OneWifi

- build/linux/makefile.inc
- build/linux/setup.sh
- source/apps/blaster/wifi_blaster.c
- source/apps/blaster/wifi_single_client_msmt.c
- source/apps/harvester/wifi_harvester.c
- source/apps/levl/wifi_levl.c
- source/apps/ocs/wifi_ocs.c
- source/apps/whix/wifi_whix.c
- source/core/wifi_ctrl_rbus_handlers.c
- source/core/wifi_mgr.c
- source/dml/rdkb/wifi_dml.c
- source/webconfig/wifi_easymesh_translator.c
Setup.sh change to create install directory within onewifi folder
Pulled additional compilation issue from sprint branch
> Changes to address compilation issue and changes in setup.sh

- source/core/wifi_ctrl.c
- source/core/wifi_ctrl.h
- source/core/wifi_ctrl_webconfig.c
Adding one more change which went into the sprint branch having commit e65ad8ee8928960f3250f0c7d531a65f34e33bbb related to Ovsh assoc table to be updated properly.
> Rebasing to latest sprint branch as of 14-November

- include/wifi_base.h
- source/core/wifi_ctrl_webconfig.c
- source/db/wifi_db.c
- source/stats/wifi_monitor.c
- source/webconfig/wifi_decoder.c
- source/webconfig/wifi_encoder.c
This pull request has two changes 
1) Channel appropriately getting updated in radio subdoc
2) Assoc frame data being sent as part of associated client subdoc
This pull request is dependent on rdk-wifi-hal changes present as part of rdk-wifi-hal pull request https://github.com/rdkcentral/rdk-wifi-hal/pull/5.
> Channel update fix and Sending Assoc frame date in associated client subdoc

- source/webconfig/wifi_easymesh_translator.c
Frame body translation changes for easymesh
Reason for change: Copy association request frame body (tagged values)
to easymesh structures.
Test Procedure: Ensure frame body response translation works fine.
Risks: Low
> Frame body translation changes for easymesh

- source/webconfig/wifi_easymesh_translator.c
Metrics collection translation changes!
> PR: Metrics collection translation changes!

- source/webconfig/wifi_easymesh_translator.c
Merge only after the "Fix for frequency band in EM" is merged in the unified-wifi-mesh repo.
> Translation of radio frequency band

- include/wifi_base.h
- source/core/wifi_ctrl.c
- source/core/wifi_ctrl_rbus_handlers.c
This reverts commit 563e9819c99979a8f8ad15acbf67339c756db8ff, reversing changes made to e4b3e0c42c79caa3852aaa04fd534de369911090.
The issues observed - 
1) Client association and disassociation logs are not coming properly. 
2) get_bus_descriptor()->bus_event_publish_fn(&m_bus_hdl, event_name, &rdata); triggering crash issues. commenting this line resolved  client association and disassociation logs issues as well.
> Revert "Merge pull request #21 from bcarlson-dev/feature/publish-mgmt-frames"

- configure.ac
- include/wifi_events.h
- lib/common/util.c
- lib/common/util.h
- source/apps/analytics/wifi_analytics.c
- source/apps/cac/wifi_cac.c
- source/apps/levl/wifi_levl.c
- source/apps/motion/wifi_motion.c
- source/apps/whix/wifi_whix.c
- source/ccsp/ccsp_api.c
- source/core/Makefile.am
- source/core/services/vap_svc_mesh_ext.c
- source/core/services/vap_svc_mesh_pod.c
- source/core/wifi_ctrl_queue_handlers.c
- source/core/wifi_ctrl_rbus_handlers.c
- source/core/wifi_easy_connect.c
- source/core/wifi_events.c
- source/db/wifi_db.c
- source/db/wifi_db_apis.c
- source/platform/linux/he_bus/inc/he_bus_common.h
- source/platform/linux/he_bus/inc/he_bus_data_conversion.h
- source/platform/linux/he_bus/src/he_bus_core.c
- source/platform/linux/he_bus/src/he_bus_data_conversion.c
- source/services/mesh/wifi_service_mesh.c
- source/stats/wifi_stats_radio_channel.c
- source/utils/wifi_util.c
- source/utils/wifi_util.h
- source/webconfig/wifi_decoder.c
- source/webconfig/wifi_encoder.c
changes from Ia1688bc99e3471a6579bfedae97e8d6f67d46ab8 to I88278d49bd8992cd3d45cd95c90ee0d8449b4461
> sync changes from sprint

- source/apps/whix/wifi_whix.c
Reason for change: Potential bugs in markers
Test Procedure: Check WIFI_MAC_%d_TOTAL_COUNT and
WIFI_INFO_PMF_CONFIG markers
Risks: None
Priority: P1
Signed-off-by:Pavithra_Sundaravadivel@comcast.com
Change-Id: Iedaa96bc172251e55a3dd93e2613ba54bdf358b7
> RDKB-58044 Needed some correction on WHiX markers

- config/TR181-WiFi-USGv2.XML
- include/wifi_base.h
- source/core/wifi_ctrl_rbus_handlers.c
- source/dml/tr_181/ml/cosa_wifi_dml.c
> Revert "RDKB-58058: Telemetry and Rbus for Transient Client Management"

- build/linux/makefile
- include/wifi_webconfig.h
- source/core/wifi_ctrl.c
- source/core/wifi_ctrl.h
- source/core/wifi_ctrl_rbus_handlers.c
- source/core/wifi_ctrl_webconfig.c
- source/webconfig/wifi_easymesh_translator.c
- source/webconfig/wifi_webconfig.c
- source/webconfig/wifi_webconfig_multivap.c
- source/webconfig/wifi_webconfig_radio.c
This PR contains changes corresponding to MultipVAP subdoc per Radio and Radio config subdoc per radio.
> Multi vap and Single Radio subdoc changes

- .gitignore
- include/webconfig_external_proto_easymesh.h
This pull request contains:
1) Remove duplicate inclusion of em_base.h.
2) Adding .gitignore file to ignore compiled .o, bin and lib files for git status command.
> Changes to remove duplicate inclusion of em_base.h and adding .gitignore files

- source/dml/tr_181/sbapi/webpa_interface.c
Reason for change: The WifiClient feature crashes in XER10. Test Procedure: 1. Enable core dump
- ulimit -c unlimited
- echo "/tmp/core.%e.%p.%h.%t" > /proc/sys/kernel/core_pattern
2. touch /nvram/wifiHarvester.
3. Connect a client.
4. Set 'Device.WiFi.X_RDKCENTRAL-COM_Report.WifiClient.MacAddress' to client
5. Set other 'Device.WiFi.X_RDKCENTRAL-COM_Report.WifiClient.' parameters.
6. Set Device.WiFi.X_RDKCENTRAL-COM_Report.WifiClient.Enable to true.
7. The json message should be in /tmp/wifiHarvester log file.
8. You should see 'event:raw.kestrel.reports.WifiSingleClient' in
/rdklogs/logs/PARODUSlog.txt.0.
9. XDP should receive the event WifiSingleClient.
10. No crash core.* files in /tmp.
Risks: None
Priority: P0
Change-Id: I0ee5579f67d9409e6a5ca6f3c4b84dcef3a0e69d
Signed-off-by: …
> RDKB-58218 : No WifiSingleClient event

- source/apps/sm/sm_neighbor_cache.c
- source/apps/sm/wifi_sm.c
This reverts commit a8ff526114b5b5a7b26c44f444f2ceaee82f4b50.
Change-Id: I16cff3e21dde1984c0c0699375b775bfc7536c54
> Revert "RDKB-58055: wifiSM log improvement"

- source/core/wifi_ctrl.c
[OneWiFi] Issue with 5GHz upper and lower band channel set when DFS is enabled
> RDKB-58635:[OneWiFi] Issue with DFS 5gl & 5gh

- source/core/services/vap_svc_mesh_ext.c
- source/utils/scheduler.c
- fixed excecution of scan timeout timer multiple times
- prevent starting multiple timers for STA connection state machine
- reserve 0 timer id for uninitialized timer Test Procedure:
- check mesh STA connection Risks: Low
Priority: P1
> LTE-2576: fixed multiple scan timeouts

- source/webconfig/wifi_decoder.c
> RDKB-57897 - Bring changes to github

- source/webconfig/wifi_decoder.c
- source/webconfig/wifi_encoder.c
Reason for change: builds are failing
Test Procedure: XB devices should compile
Risks: Low
Priority:P0
> RDKBWIFI-24: fix compilation issue

- source/apps/levl/wifi_levl.c
Reason for change: Rearranging levl mutex unlocks to avoid OneWifi deadlock. Test Procedure:
1. Load the device with the above mentioned build.
2. Check whether the device is connected to the cloud by the below print in /rdklogs/logs/agent.txt
3.Enabled the LEVL RFC with the below command,
dmcli eRT setv Device.DeviceInfo.X_RDKCENTRAL-COM_RFC.Feature.Levl.Enable bool true
4. Connect, disconnect client and observe for timeout errors in  rdklogs/logs/ADVSEClog.txt.0
Risks: Medium
Priority: P0
> RDKB-58787: WiFi radio temperature event unsubscribe timeout

- include/webconfig_external_proto_easymesh.h
- include/wifi_base.h
- include/wifi_events.h
- source/apps/em/wifi_em.c
- source/apps/em/wifi_em.h
- source/apps/sta_manager/wifi_sta_manager.c
- source/apps/wifi_apps.c
- source/core/wifi_events.c
- source/webconfig/wifi_decoder.c
- source/webconfig/wifi_easymesh_translator.c
- source/webconfig/wifi_encoder.c
- source/webconfig/wifi_webconfig_easymesh_config.c
- source/webconfig/wifi_webconfig_sta_manager.c
EM APP Changes for encode/decode/translation of policy/beacon datas between EasyMesh Agent and OneWifi
> Encode/decode/translation of policy/beacon related datas between EasyMesh Agent and OneWifi

- include/webconfig_external_proto_easymesh.h
- source/webconfig/wifi_easymesh_translator.c
Add haultype configuration support and remove mesh sta configuration in webconfig translator
> Add haultype configuration support and remove mesh sta configuration

- source/apps/sta_manager/wifi_sta_manager.c
Additional check for Beacon report Responses.
Disabling test encode/decode.
> Check for Proper Beacon report response

- include/wifi_base.h
- source/apps/em/wifi_em.c
- source/stats/wifi_stats_neighbor_report.c
- source/stats/wifi_stats_radio_channel.c
- source/webconfig/wifi_decoder.c
- source/webconfig/wifi_easymesh_translator.c
- source/webconfig/wifi_encoder.c
- source/webconfig/wifi_webconfig_em_channel_stats.c
RDKB-59209: EM App - Channel scan changes
Reason for change: 1) Modify the channel scan implementation based on operating class and channel.
2) Added additional scan mode WIFI_RADIO_SCAN_MODE_SELECT_CHANNELS to scan only requested channels.
3) Updated ScannerMac along with scan results
4) Added changes to stop scan once completed the scan.
5) Updated aggregate_scan_duration and scan_type as part of channel_scan_result_t structure.
6) Updated proper formatting to scan related changes
Test Procedure: Ensure channel scan results are received in agent side and then to controller cli upon request for channel scan. Risks: Medium
Priority: P1
> RDKB-59209: EM App - Channel scan changes

- build/linux/setup.sh
Reason for change: setup.sh change to checkout sta mgr code.
Test Procedure: Station Manager should checkout and buuld properly.
Risks: Low
> RDKB-59277 : Build script change for checking out sta Mgr.

- build/linux/makefile
- source/utils/mtrx/inc/mtrx.h
- source/utils/mtrx/src/mtrx.c
- source/utils/wifi_util.c
- source/utils/wifi_util.h
Reason for change: Added source code for CSI Matrix calculation.
Test Procedure:1. Load the OneWifi build.
2. Test basic features.
Priority: P2
Risks: Low
Signed-off-by: aniketnarsinhbhai_Patel@comcast.com
> RDKB-59430:[OneWifi]CSI Matrix calculation

- source/platform/linux/he_bus/src/he_bus_connection.c
In certain, semi-random, situations, the `he_bus` will read more data from the socket than it is told it needs to read. Previously, it would only allocate what it was told what needs to read but copy over all of the data it received. In those specific situations this would cause a "heap memory overflow" resulting in a SEGFAULT, crashing `unified-wifi-mesh`. 
One solution would be to simply change the allocation to the amount of bytes received however based on the while loop, it appears that the intended behavior is that this buffer should not be more than `total_recv_data_len` long, therefore we ignore the extraneous bytes, particularly since this is parsed later.
At least within unified-wifi-mesh, making repeated calls and subscription callbacks over the bus, this …
> RDKBWIFI-33: Fixes SEGFAULT present in `he_bus` when recieved data is more than expected

- source/db/wifi_db_apis.c
- source/dml/tr_181/ml/cosa_wifi_internal.c
Reason for change:  DEBUG BUILD
Test Procedure: NA
Risks: Low
> SHARMAN-3535 : WPS disable config failed to persist after reboot

- build/openwrt/MT7966.config
- build/openwrt/Makefile_package
The CTRL openWRT related configuration changes. The golden .config file and makefile to enable CTRL for OpenWRT systems.
> RDKB-59737: EasyMesh CTRL configuration changes.

- source/webconfig/wifi_ovsdb_translator.c
XLE-WNC
Reason for change: Added mutex lock to avoid race condition during encode and decode.
Test Procedure: Multiple reboot or software upgrade and verify VAPs are up and clients able to connect.
Risks: Low
Priority: P1
> LTE-2656 SSIDs are enabled in tr-181 but vaps are down in driver level

- build/linux/bpi/setup.sh
- build/linux/rpi/setup.sh
To ensure hostapd & rdk-wifi-hal compilation is successful for Raspberry Pi and Banana Pi
> Managed WiFi Phase 2

- source/sampleapps/wifievents_consumer_sample.c
Reason for change: Added features on sample APP to save CSI data on json_format.
Test Procedure: 1. Load the OneWifi build.
2. Connect a station to gateway.
3. Execute the below command: $ wifi_events_consumer -e 7 -i 300 -n 20 &
-e 7 : subscribe to csi data
-i [csi data interval] : default 500ms min 100 max 30000 -n [num_of_samples to be written to a file]
4. check for the index by running the below data model command $ dmcli eRT getv Device.WiFi.X_RDK_CSI.
5. Provide input station mac address and enable CSI data collection by executing command, example as mentioned below $ dmcli eRT setv Device.WiFi.X_RDK_CSI.[index].ClientMaclist string F0:46:3B:5B:EF:D9 $ dmcli eRT setv Device.WiFi.X_RDK_CSI.[index].Enable bool true
6. As soon as the required samples are collected, …
> RDKB-60433: Sample APP now saves CSI data in JSON format

- config/TR181-WiFi-USGv2.XML
- source/core/services/vap_svc_private.c
- source/dml/tr_181/ml/cosa_wifi_dml.c
- source/utils/wifi_util.c
- source/webconfig/wifi_decoder.c
- source/webconfig/wifi_encoder.c
Align memcpy to be architecture independent and remove the Repurposed Radius implementation for WPA/WPA2/WPA3 Personal, PT modes. Update from hotspot interfaces alone.
> RDKB-60035: Managed WiFi Phase 2 

- build/openwrt/setup.sh
- config/openwrt/banana-pi/wifi_interface_up.sh
- include/wifi_base.h
- include/wifi_events.h
- source/core/wifi_ctrl.c
- source/core/wifi_ctrl_queue_handlers.c
- source/core/wifi_ctrl_rbus_handlers.c
- source/webconfig/wifi_easymesh_translator.c
Reason for change: Implement channel change based on CSA beacon frame.
Test Procedure: Ensure channel change work in easymesh network.
Risks: Medium
Priority: P1
> RDKB-60610: Implement channel change based on CSA beacon frame.

- build/openwrt/Makefile_package
- build/openwrt/makefile
- build/openwrt/makefile.inc
- build/openwrt/setup.sh
RDKB-60610, RDKCOM-5329 changes related to resolving OpenWRT build failure.
> RDKB-60610, RDKCOM-5329 changes related to OpenWRT build 

- scripts/OneWiFi_Selfheal.sh
XER10-2018 : Port 6g ecomode Changes to release
Reason for change: Cherrypicking the following github changes
XER10-995: Add selfheal support for XER10 #245
Since xer10 supports eco mode feature as well as its a tri band product, this change mainly includes the following modifcations in script:
Add 6G eco mode check for as well as in the script.
Add XER10 device model support.
Test Procedure: Make sure onewifi_selfheal is working for XER10
Risks: Low
Priority: P1
> XER10-2018: Port 6g ecomode Changes to release and XER10 model support changes in Onewifi_selfheal to main

- scripts/OneWiFi_Selfheal.sh
- scripts/mesh_setip.sh
- source/core/wifi_ctrl.c
- source/db/wifi_db.c
- source/db/wifi_db_apis.c
- source/dml/tr_181/ml/cosa_wifi_dml.c
- source/utils/wifi_util.c
- source/webconfig/wifi_ovsdb_translator.c
Reason for change: Add XF10 changes.
Test Procedure: None
Risks: None
Priority: P0
> XF10-34 : Add XF10 support

- source/core/wifi_multidoc_webconfig.c
Needed reconfiguration for decoding the hotspot blob received from webconfig and to reduce the delay in applying the blob config.
> RDKB-60918: Refactoring execution of blob for hotspot vaps.

- build/linux/stamgr_setup.sh
- build/openwrt/stamgr_setup.sh
Update the build script to use the 25Q3_Sprint branch for sta_mgr changes.
> RDKB-61305: Update the build script to use 25Q3_Sprint branch

- source/core/services/vap_svc.h
- source/core/services/vap_svc_mesh_ext.c
- Topology optimization fails, 5GHz Backhaul connectivity is not getting established
- Optimization fails but parent change is successfull
> DTMESH-590 & DTMESH-585 : Address optimisation failures

- .github/release.yml
Create release.yml file, required for automation of release notes generation.
> RDKB-61715 add release.yml

- source/stats/wifi_stats_radio_channel.c
RDKB-58211-Removing OCS (off channel scanning) for secondary channels
Reason for change: Removed secondary channels from the list of channels for Off channel scanning.
1. Load the custom build
2. Verify that NOC push table "Wifi_Stats_Config"
`/usr/opensync/tools/ovsh s Wifi_Stats_Config  -w radio_type==5G`
3. Check the correct working channel
`wl -i wl1.1 chanspec`
4. check if the current working channel is DFS if yes disable the DFS
`dmcli eRT getv Device.DeviceInfo.X_RDKCENTRAL-COM_RFC.Feature.DFS.Enable`
5. For testing purpose reduce sampling and reporting interval for 5G OCS
`/usr/opensync/tools/ovsh u Wifi_Stats_Config -w survey_type==off-chan -w radio_type==5G -w stats_type==neighbor reporting_interval:=60 /usr/opensync/tools/ovsh u Wifi_Stats_Config -w …
> RDKB-58211 Removing OCS (off channel scanning) for secondary channels
